import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  hidden: {
    display: 'none',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  screenTransitionContainer: {
    flex: 1,
    overflow: 'hidden',
    width: '100%',
  },
  authFullScreen: {
    backgroundColor: '#091C10',
    flex: 1,
    height: '100%',
    overflow: 'hidden',
    width: '100%',
  },
  authBg: {
    flex: 1,
    height: '100%',
    overflow: 'hidden',
    width: '100%',
  },
  authOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0000002A',
  },
  authScene: {
    alignSelf: 'stretch',
    flex: 1,
    overflow: 'hidden',
    width: '100%',
  },
  authTopZone: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  authBottomZone: {
    overflow: 'hidden',
    width: '100%',
  },
  authBrandStart: {
    alignItems: 'center',
  },
  authBrandFinal: {
    alignItems: 'center',
    marginTop: 14,
  },
  authLogoOutline: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 2,
    height: 116,
    justifyContent: 'center',
    width: 116,
  },
  authBrandText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 28,
    marginTop: 16,
    textAlign: 'center',
  },
  stagesScrollContent: {
    flexGrow: 1,
    paddingBottom: 112,
  },
  stagesScreen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  stagesTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  backButton: {
    alignItems: 'center',
    borderColor: '#C7D2CA',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 14,
  },
  backButtonText: {
    color: '#2C4B39',
    fontSize: 14,
    fontWeight: '700',
  },
  codeButton: {
    alignItems: 'center',
    backgroundColor: '#15863F',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 78,
    paddingHorizontal: 16,
  },
  codeButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  passportHeaderButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#DCE7DE',
    borderRadius: 999,
    borderWidth: 1,
    elevation: 2,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 18,
    shadowColor: '#101828',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
  },
  passportHeaderButtonText: {
    color: '#15863F',
    fontSize: 14,
    fontWeight: '800',
  },
  headerSpacer: {
    minWidth: 78,
  },
  stagesHeader: {
    marginBottom: 22,
  },
  stagesTitle: {
    color: '#17251C',
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 36,
  },
  stagesSubtitle: {
    color: '#5F7065',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 8,
  },
  stageHeaderSubtitle: {
    color: '#5F7065',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  stageGrid: {
    columnGap: 9,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    rowGap: 9,
  },
  homeClearButton: {
    marginTop: 6,
  },
  stageCard: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'flex-start',
    minHeight: 172,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 62,
    position: 'relative',
    shadowColor: '#0e2f19',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 34,
    marginBottom: 0,
    flexBasis: '47%',
    flexGrow: 1,
    flexShrink: 1,
    maxWidth: '48%',
  },
  stageCardPressed: {
    backgroundColor: '#FAFCFB',
    borderColor: '#DCE8E2',
  },
  stageIconBox: {
    alignItems: 'center',
    borderRadius: 999,
    bottom: 14,
    height: 40,
    justifyContent: 'center',
    position: 'absolute',
    right: 14,
    width: 40,
  },
  stageIconBoxGreen: {
    backgroundColor: 'rgba(21, 134, 63, 0.3)',
  },
  stageIconBoxMint: {
    backgroundColor: 'rgba(16, 185, 129, 0.3)',
  },
  stageIconBoxAqua: {
    backgroundColor: 'rgba(20, 184, 166, 0.3)',
  },
  stageIconBoxLime: {
    backgroundColor: 'rgba(101, 163, 13, 0.3)',
  },
  stageIconBoxSky: {
    backgroundColor: 'rgba(14, 165, 233, 0.3)',
  },
  stageIconBoxOrange: {
    backgroundColor: 'rgba(251, 146, 60, 0.3)',
  },
  stageName: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 21,
    minHeight: 42,
    paddingRight: 18,
    textAlign: 'left',
  },
  globalJournalButton: {
    alignItems: 'flex-start',
    backgroundColor: '#15863F',
    borderColor: '#15863F',
    borderRadius: 999,
    borderWidth: 1,
    gap: 4,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 62,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  globalJournalButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
  },
  globalJournalButtonMeta: {
    color: '#DCE9DF',
    fontSize: 13,
    fontWeight: '700',
  },
  testClearButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderColor: '#D92D20',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  testClearButtonText: {
    color: '#B42318',
    fontSize: 15,
    fontWeight: '800',
  },
  homeNoticeText: {
    color: '#15863F',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 16,
    textAlign: 'center',
  },
  homeErrorText: {
    color: '#B42318',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 16,
    textAlign: 'center',
  },
  menuScrollContent: {
    flexGrow: 1,
    paddingBottom: 112,
  },
  menuScreen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  menuHeader: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    marginBottom: 14,
    padding: 16,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.055,
    shadowRadius: 14,
  },
  menuAvatar: {
    alignItems: 'center',
    backgroundColor: '#15863F',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  menuAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  menuUserTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  menuUserName: {
    color: '#111827',
    fontSize: 21,
    fontWeight: '800',
    lineHeight: 27,
    marginTop: 1,
  },
  menuUserRole: {
    color: '#65756B',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 2,
  },
  menuHeaderExitButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    height: 40,
    width: 40,
    borderRadius: 999,
  },
  menuStatsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
  },
  menuStatCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    minHeight: 92,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  menuStatValue: {
    color: '#17251C',
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
  },
  menuStatLabel: {
    color: '#65756B',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 4,
  },
  menuSection: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 14,
    overflow: 'hidden',
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.045,
    shadowRadius: 12,
  },
  menuItem: {
    alignItems: 'center',
    borderBottomColor: '#EEF2F0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 70,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  menuItemTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  menuItemTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 21,
  },
  menuItemSubtitle: {
    color: '#65756B',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  menuItemArrow: {
    color: '#9CA3AF',
    fontSize: 28,
    fontWeight: '500',
    lineHeight: 30,
  },
  menuLogoutButton: {
    marginTop: 2,
  },
  menuNoticeText: {
    color: '#15863F',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
    textAlign: 'center',
  },
  homeScannerIcon: {
    height: 28,
    width: 28,
  },
  tasksPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 18,
    padding: 14,
  },
  tasksHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tasksScreenContent: {
    flexGrow: 1,
    paddingBottom: 112,
  },
  tasksScreen: {
    flex: 1,
    paddingHorizontal: 20,
  },
  tasksPageHeader: {
    marginBottom: 16,
  },
  tasksPageTitle: {
    color: '#111827',
    fontSize: 21,
    fontWeight: '800',
    lineHeight: 27,
  },
  tasksPageMeta: {
    color: '#6B7280',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 4,
  },
  tasksList: {
    gap: 12,
  },
  tasksEmptyCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
  },
  tasksEmptyTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
    marginBottom: 4,
  },
  tasksTitle: {
    color: '#17251C',
    fontSize: 18,
    fontWeight: '800',
  },
  tasksBadge: {
    backgroundColor: '#E8F0EA',
    borderRadius: 999,
    color: '#15863F',
    fontSize: 13,
    fontWeight: '800',
    minWidth: 30,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    textAlign: 'center',
  },
  tasksBadgeWarning: {
    backgroundColor: '#FFF1F0',
    color: '#B42318',
  },
  tasksEmpty: {
    color: '#65756B',
    fontSize: 14,
    lineHeight: 20,
  },
  taskItem: {
    backgroundColor: '#15863F0D',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  taskItemWarning: {
    backgroundColor: '#FFF7F5',
    borderColor: '#D92D20',
  },
  taskItemHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  taskItemTitle: {
    color: '#1B3023',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  taskStatus: {
    color: '#15863F',
    fontSize: 13,
    fontWeight: '800',
  },
  taskStatusWarning: {
    color: '#B42318',
  },
  taskItemText: {
    color: '#1B3023',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
  },
  taskItemMeta: {
    color: '#65756B',
    fontSize: 13,
    lineHeight: 18,
  },
  taskSubList: {
    borderTopColor: '#DCE7DE',
    borderTopWidth: 1,
    gap: 8,
    marginTop: 10,
    paddingTop: 10,
  },
  taskSubItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  taskSubItemTitle: {
    color: '#1B3023',
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 18,
  },
  taskSubItemMeta: {
    color: '#65756B',
    flexShrink: 0,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  tasksMore: {
    color: '#5F7065',
    fontSize: 13,
    fontWeight: '700',
  },
  cardsScrollContent: {
    flexGrow: 1,
  },
  cultureFormScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
  },
  cardsScreen: {
    backgroundColor: 'transparent',
    flex: 1,
    paddingHorizontal: 16,
    paddingBottom: 28,
    paddingTop: 18,
  },
  fixedCardsScreen: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  calendarSummaryHeader: {
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    paddingBottom: 14,
    zIndex: 2,
  },
  fixedCardsControls: {
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
  },
  globalJournalTitle: {
    color: '#111827',
    fontSize: 21,
    fontWeight: '800',
    lineHeight: 27,
    marginBottom: 16,
  },
  globalJournalFilterScroll: {
    marginHorizontal: -16,
  },
  globalJournalFilterRow: {
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 18,
    paddingHorizontal: 16,
  },
  fixedCardsScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 32,
  },
  fixedCardsScrollContentWithActions: {
    paddingBottom: 126,
  },
  fixedAddButtonBar: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderTopWidth: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: 18,
    left: 0,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 28,
    position: 'absolute',
    right: 0,
  },
  cardsHeader: {
    marginBottom: 18,
  },
  cardsTitle: {
    color: '#17251C',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  cardsSubtitle: {
    color: '#5F7065',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 6,
  },
  eventFormCardTitle: {
    color: '#17251C',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 30,
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 12,
  },
  searchBox: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 40,
    borderWidth: 1,
    elevation: 2,
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    height: 52,
    paddingHorizontal: 14,
    shadowColor: '#101828',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  searchIcon: {
    color: '#9AA3AF',
    fontSize: 19,
    fontWeight: '700',
    lineHeight: 22,
    marginTop: 1,
    textAlign: 'center',
    width: 22,
  },
  searchInput: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    color: '#111827',
    flex: 1,
    fontSize: 16,
    height: 52,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 18,
  },
  filterButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 999,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 13,
    position: 'relative',
    shadowColor: '#101828',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  filterButtonActive: {
    backgroundColor: '#15863F',
    borderColor: '#15863F',
    shadowColor: '#15863F',
    shadowOpacity: 0.18,
  },
  filterButtonText: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '600',
  },
  filterButtonTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  codeInputRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 10,
  },
  codeInput: {
    flex: 1,
    minWidth: 0,
  },
  generateButton: {
    alignItems: 'center',
    backgroundColor: '#15863F14',
    borderColor: '#15863F4D',
    borderWidth: 1,
    borderRadius: 16,
    flexShrink: 0,
    justifyContent: 'center',
    minHeight: 56,
    width: 56,
  },
  generateButtonDisabled: {
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: '#15863F',
    borderRadius: 999,
    flex: 1,
    justifyContent: 'center',
    minHeight: 74,
    marginBottom: 18,
  },
  fixedAddButton: {
    backgroundColor: '#15863F',
    borderRadius: 999,
    elevation: 5,
    minHeight: 60,
    marginBottom: 0,
    shadowColor: '#15863F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
  },
  calendarScreen: {
    flex: 1,
    position: 'relative',
  },
  calendarScroll: {
    flex: 1,
  },
  calendarPinnedContent: {
    backgroundColor: 'transparent',
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 8,
  },
  calendarContent: {
    paddingHorizontal: 18,
    paddingTop: 9,
    paddingBottom: 130,
  },
  calendarStripPanel: {
    marginBottom: 30,
    paddingBottom: 12,
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  calendarMonthHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  calendarHeaderRight: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  calendarNavButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF1EF',
    borderRadius: 999,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  calendarNavButtonText: {
    color: '#17251C',
    fontSize: 26,
    fontWeight: '700',
    lineHeight: 28,
  },
  calendarMonthTitle: {
    color: '#161B24',
    flex: 1,
    fontSize: 19,
    fontWeight: '800',
    textAlign: 'center',
  },
  calendarModeChip: {
    alignItems: 'center',
    backgroundColor: '#EAF6EF',
    borderRadius: 999,
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  calendarModeChipText: {
    color: '#15863F',
    fontSize: 15,
    fontWeight: '800',
  },
  calendarDayStrip: {
    alignItems: 'stretch',
    gap: 10,
    paddingHorizontal: 2,
  },
  calendarDayCell: {
    alignItems: 'center',
    borderRadius: 999,
    minWidth: 42,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  calendarDayCellActive: {
    backgroundColor: '#15863F',
  },
  calendarDayCellMarked: {
    backgroundColor: '#EAF6EF',
  },
  calendarDayName: {
    color: '#65706A',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
    textTransform: 'capitalize',
  },
  calendarDayNameActive: {
    color: '#FFFFFF',
  },
  calendarDayNumber: {
    color: '#323840',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  calendarDayNumberActive: {
    color: '#FFFFFF',
  },
  calendarAlertList: {
    gap: 10,
  },
  calendarAlert: {
    borderColor: '#B42318',
    borderWidth: 2,
    gap: 5,
    marginTop: 8,
    padding: 14,
  },
  calendarAlertTitle: {
    color: '#B42318',
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  calendarAlertText: {
    color: '#65756B',
    fontSize: 14,
    lineHeight: 20,
  },
  surfacePanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#F0F2F4',
    borderRadius: 20,
    borderWidth: 1,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
  },
  dateActionPanel: {
    gap: 12,
    marginTop: 18,
    padding: 16,
  },
  calendarRecordsPanel: {
    overflow: 'hidden',
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 16,
  },
  calendarRecordsDivider: {
    backgroundColor: '#15863F',
    borderRadius: 2,
    height: 2,
    marginTop: 10,
    marginBottom: 14,
  },
  dateRecordsScroll: {
    maxHeight: 360,
  },
  dateRecordsContent: {
    gap: 12,
    paddingBottom: 2,
  },
  calendarStageMoveFooter: {
    marginTop: 18,
  },
  calendarBottomActions: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    bottom: 0,
    flexDirection: 'row',
    gap: 12,
    left: 0,
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 28,
    position: 'absolute',
    right: 0,
  },
  calendarStageMoveButton: {
    borderRadius: 999,
    flex: 1,
  },
  calendarStageMoveButtonText: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 19,
  },
  calendarAddEventButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#15863F',
    borderRadius: 999,
    borderWidth: 2,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  calendarAddEventButtonText: {
    color: '#15863F',
    fontSize: 36,
    fontWeight: '300',
    lineHeight: 40,
    marginTop: -3,
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: '#00000066',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  confirmModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    gap: 12,
    padding: 16,
    width: '100%',
  },
  confirmModalTitle: {
    color: '#17251C',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 25,
  },
  confirmModalText: {
    color: '#65756B',
    fontSize: 15,
    lineHeight: 21,
  },
  confirmModalNotice: {
    backgroundColor: '#FFF7F5',
    borderColor: '#F2B8B5',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  confirmModalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  confirmModalButton: {
    borderRadius: 999,
    flex: 1,
    minHeight: 50,
  },
  dateActionTitle: {
    color: '#17251C',
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'left',
  },
  dateActionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'flex-start',
  },
  blockedNotice: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#F1D6D2',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  blockedNoticeText: {
    color: '#B42318',
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  stageActionErrorNotice: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#F1D6D2',
    borderRadius: 14,
    borderWidth: 2,
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  dateEntryToggle: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#15863F',
    borderRadius: 18,
    borderWidth: 2,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  dateEntryToggleActive: {
    backgroundColor: '#15863F',
  },
  dateEntryToggleText: {
    color: '#15863F',
    fontSize: 32,
    fontWeight: '400',
    lineHeight: 34,
    marginTop: -2,
  },
  dateEntryToggleTextActive: {
    color: '#FFFFFF',
  },
  dateActionDivider: {
    backgroundColor: '#E6EDE7',
    height: 1,
    marginTop: 6,
  },
  dateEntryToggleIcon: {
    height: 16,
    position: 'relative',
    width: 16,
  },
  dateEntryToggleLine: {
    backgroundColor: '#15863F',
    borderRadius: 1,
    height: 2,
    left: 0,
    position: 'absolute',
    top: 7,
    width: 16,
  },
  dateEntryToggleLineActive: {
    backgroundColor: '#FFFFFF',
  },
  dateEntryToggleLineVertical: {
    transform: [{ rotate: '90deg' }],
  },
  journalPanel: {
    gap: 10,
    paddingBottom: 16,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  journalTitle: {
    color: '#17251C',
    fontSize: 18,
    fontWeight: '800',
  },
  journalEmpty: {
    color: '#65756B',
    fontSize: 14,
    lineHeight: 20,
  },
  journalItem: {
    gap: 4,
  },
  journalItemWarning: {
    // keep warning styling without an internal divider
  },
  journalItemTitle: {
    color: '#1B3023',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    minWidth: 0,
  },
  journalItemDate: {
    color: '#5F7065',
    fontSize: 13,
    lineHeight: 18,
  },
  journalItemText: {
    color: '#5F7065',
    fontSize: 14,
    lineHeight: 19,
  },
  operationHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  operationActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: 6,
  },
  operationActionButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  globalJournalCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 16,
    borderWidth: 1,
    elevation: 2,
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 16,
    position: 'relative',
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.045,
    shadowRadius: 30,
  },
  globalJournalCardWarning: {
    backgroundColor: '#FFF7F5',
    borderColor: '#D92D20',
    borderWidth: 2,
  },
  globalJournalCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginHorizontal: -4,
    marginTop: -4,
    padding: 4,
  },
  globalJournalCardTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  globalJournalCardHeaderSide: {
    alignItems: 'flex-end',
    gap: 4,
  },
  globalJournalBadge: {
    backgroundColor: '#15863F',
    borderRadius: 999,
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    minWidth: 30,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    textAlign: 'center',
  },
  globalJournalOpenCardButton: {
    alignItems: 'center',
    backgroundColor: '#E8F0EA',
    borderRadius: 999,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 40,
    paddingHorizontal: 12,
  },
  globalJournalOpenCardButtonText: {
    color: '#15863F',
    fontSize: 14,
    fontWeight: '800',
  },
  globalJournalCollapseLink: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  globalJournalCollapseLinkText: {
    color: '#15863F',
    fontSize: 14,
    fontWeight: '800',
  },
  globalJournalEventList: {
    gap: 0,
    marginTop: 8,
  },
  statusSummary: {
    borderTopColor: '#E6EDE7',
    borderTopWidth: 1,
    gap: 4,
    paddingTop: 12,
  },
  statusSummaryFirst: {
    borderTopWidth: 0,
    paddingTop: 0,
  },
  statusSummaryTitle: {
    color: '#1B3023',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    minWidth: 0,
  },
  statusSummaryTitleDanger: {
    color: '#B42318',
  },
  statusSummaryText: {
    color: '#5F7065',
    fontSize: 14,
    lineHeight: 19,
  },
  eventTime: {
    color: '#65756B',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  eventRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  eventContent: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  dateEmptyText: {
    color: '#7A8491',
    fontSize: 14,
    lineHeight: 20,
  },
  dateSectionTitle: {
    color: '#17251C',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 4,
  },
  dateEntryPanel: {
    gap: 12,
  },
  dateEntriesDivider: {
    backgroundColor: '#E6EDE7',
    borderRadius: 1,
    height: 2,
  },
  eventActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  eventIconActions: {
    flexDirection: 'row',
    flexShrink: 0,
    gap: 4,
  },
  eventIconButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  eventActionButton: {
    alignItems: 'center',
    backgroundColor: '#15863F1A',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
  },
  eventActionButtonText: {
    color: '#15863F',
    fontSize: 13,
    fontWeight: '800',
  },
  eventDangerButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
  },
  eventDangerButtonText: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '800',
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  actionChip: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#15863F',
    borderRadius: 999,
    borderWidth: 2,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 14,
  },
  actionChipActive: {
    backgroundColor: '#15863F',
    borderColor: '#15863F',
  },
  actionChipText: {
    color: '#15863F',
    fontSize: 13,
    fontWeight: '600',
  },
  actionChipTextActive: {
    color: '#FFFFFF',
  },
  inlineForm: {
    gap: 10,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0,
  },
  plantCardList: {
    gap: 10,
  },
  plantCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 16,
    elevation: 2,
    // minHeight: 92,
    paddingHorizontal: 16,
    paddingVertical: 16,
    position: 'relative',
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.045,
    shadowRadius: 30,
  },
  plantCardActive: {
    borderColor: '#A7F3C4',
    borderWidth: 1.5,
  },
  plantCardWarning: {
    backgroundColor: '#FFF7F5',
    borderColor: '#D92D20',
    borderWidth: 2,
  },
  plantCardName: {
    color: '#111827',
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
    paddingRight: 34,
  },
  plantCardCode: {
    color: '#5F7065',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 5,
  },
  plantCardHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
    paddingRight: 38,
  },
  plantCardActions: {
    alignItems: 'flex-start',
    marginTop: 10,
  },
  plantCardActionButton: {
    alignItems: 'center',
    backgroundColor: '#15863F1A',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
  },
  plantCardActionButtonText: {
    color: '#15863F',
    fontSize: 13,
    fontWeight: '800',
  },
  plantCardStatusDot: {
    borderRadius: 7,
    height: 10,
    position: 'absolute',
    right: 18,
    top: 18,
    width: 10,
    zIndex: 1,
  },
  plantCardStatusDotGroup: {
    flexDirection: 'row',
    gap: 6,
    position: 'absolute',
    right: 18,
    top: 18,
    zIndex: 1,
  },
  plantCardStatusDotInline: {
    borderRadius: 7,
    height: 14,
    width: 14,
  },
  plantCardStatusDotActive: {
    backgroundColor: '#15863F',
  },
  plantCardStatusDotDraft: {
    backgroundColor: '#9CA3AF',
  },
  plantCardStatusDotProblem: {
    backgroundColor: '#EF4444',
  },
  plantCardStatusDotPartial: {
    backgroundColor: '#F59E0B',
  },
  plantCardMetaGrid: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 12,
  },
  plantCardMetaBlock: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: 6,
  },
  plantCardMetaValue: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '400',
    lineHeight: 14,
  },
  plantCardCodePill: {
    backgroundColor: '#F3F4F6',
    borderRadius: 7,
    color: '#6B7280',
    flexShrink: 0,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  plantCardMetaDanger: {
    color: '#B42318',
    fontWeight: '800',
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 10,
    borderWidth: 1,
    padding: 24,
  },
  emptyStateText: {
    color: '#65756B',
    fontSize: 18,
    fontWeight: '600',
  },
  formPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#F0F2F4',
    borderRadius: 22,
    borderWidth: 1,
    gap: 14,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 18,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
  },
  cultureFormFooter: {
    gap: 12,
    marginTop: 18,
  },
  formSectionDivider: {
    backgroundColor: '#EEF0F2',
    height: 1,
  },
  formBlockGap: {
    height: 14,
  },
  formFieldGap: {
    height: 10,
  },
  formSectionTitle: {
    color: '#9AA3AF',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 16,
    marginTop: 8,
  },
  editActionTitle: {
    color: '#111827',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 30,
    marginBottom: 2,
  },
  noticeBox: {
    backgroundColor: '#FFF7E6',
    borderColor: '#F0C36A',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  selectButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF0F2',
    // borderRadius: 999,
    // borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 52,
    paddingHorizontal: 0,
  },
  selectButtonDisabled: {
    opacity: 1,
  },
  selectButtonText: {
    color: '#000000',
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
  },
  selectButtonArrow: {
    alignItems: 'center',
    flexShrink: 0,
    height: 24,
    justifyContent: 'center',
    marginLeft: 12,
    width: 24,
  },
  dropdownList: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF0F2',
    borderRadius: 16,
    borderWidth: 1,
    elevation: 8,
    marginTop: 6,
    maxHeight: 260,
    zIndex: 20,
  },
  dropdownItem: {
    borderBottomColor: '#E6EDE7',
    borderBottomWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dropdownItemText: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  dropdownItemMeta: {
    color: '#5F7065',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  bottomSheetRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  bottomSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#00000066',
  },
  bottomSheetPanel: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '78%',
    paddingBottom: 18,
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  bottomSheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#CBD5D0',
    borderRadius: 999,
    height: 5,
    marginBottom: 12,
    width: 44,
  },
  bottomSheetTitle: {
    color: '#132017',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  bottomSheetOptions: {
    paddingBottom: 8,
  },
  bottomSheetOption: {
    borderBottomColor: '#E6EDE7',
    borderBottomWidth: 1,
    minHeight: 52,
    justifyContent: 'center',
    paddingHorizontal: 4,
    paddingVertical: 12,
  },
  bottomSheetOptionText: {
    color: '#1B3023',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
  },
  bottomSheetCustomField: {
    paddingTop: 16,
  },
  bottomSheetCustomLabel: {
    color: '#132017',
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
    marginBottom: 8,
  },
  bottomSheetInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF0F2',
    borderRadius: 16,
    borderWidth: 1,
    color: '#132017',
    fontSize: 16,
    lineHeight: 21,
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  sectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  preventionItem: {
    backgroundColor: '#15863F0D',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  preventionItemTitle: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  preventionItemText: {
    color: '#5F7065',
    fontSize: 14,
    lineHeight: 19,
  },
  preventionEditor: {
    gap: 10,
  },
  inlineActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  inlineActionButton: {
    alignItems: 'center',
    backgroundColor: '#15863F1A',
    borderRadius: 999,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  inlineActionButtonText: {
    color: '#15863F',
    fontSize: 13,
    fontWeight: '800',
  },
  inlineDangerButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderRadius: 999,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  inlineDangerButtonText: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '800',
  },
  toggleRow: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    padding: 0,
  },
  toggleButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#15863F',
    borderWidth: 2,
    borderRadius: 999,
    flexBasis: '48%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  toggleButtonActive: {
    backgroundColor: '#15863F',
  },
  toggleButtonText: {
    color: '#526258',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'center',
  },
  toggleButtonTextActive: {
    color: '#FFFFFF',
  },
  secondaryOutlineButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#15863F',
    borderWidth: 1,
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 16,
  },
  transparentOutlineButton: {
    backgroundColor: 'transparent',
  },
  secondaryOutlineButtonText: {
    color: '#15863F',
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 19,
  },
  keyboardView: {
    flex: 1,
    overflow: 'hidden',
    width: '100%',
  },
  scrollContent: {
    flexGrow: 1,
  },
  screen: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  brand: {
    alignItems: 'center',
    marginBottom: 40,
  },
  logoMark: {
    alignItems: 'center',
    backgroundColor: '#F0FFF6',
    borderRadius: 18,
    height: 72,
    justifyContent: 'center',
    marginBottom: 14,
    shadowColor: '#CCF8DE',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.26,
    shadowRadius: 18,
    width: 72,
  },
  logoImage: {
    height: 38,
    width: 38,
  },
  header: {
    alignItems: 'center',
  },
  title: {
    color: '#101828',
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 36,
    textAlign: 'center',
  },
  subtitle: {
    color: '#53665B',
    fontSize: 16,
    lineHeight: 22,
  },
  authPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#F0F2F4',
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 24,
    paddingBottom: 28,
    paddingTop: 26,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.06,
    shadowRadius: 24,
  },
  authPanelFloating: {
    alignSelf: 'stretch',
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    height: '100%',
    paddingTop: 24,
    paddingHorizontal: 24,
    width: '100%',
  },
  formHeader: {
    marginBottom: 8,
  },
  formTitle: {
    color: '#566170',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 20,
  },
  form: {
    gap: 22,
  },
  field: {
    gap: 6,
  },
  label: {
    color: '#65756B',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 18,
  },
  passwordRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  forgotPasswordText: {
    color: '#15863F',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  forgotPasswordTextCenter: {
    color: '#15863F',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    textAlign: 'center',
  },
  authInput: {
    backgroundColor: '#F9FAFB',
    borderColor: '#EEF0F2',
    borderRadius: 16,
    borderWidth: 1,
    color: '#101828',
    fontSize: 16,
    minHeight: 56,
    paddingHorizontal: 18,
    shadowColor: '#101828',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  authInputRow: {
    justifyContent: 'center',
    position: 'relative',
  },
  authInputIcon: {
    left: 18,
    position: 'absolute',
    zIndex: 2,
  },
  authInputWithIcon: {
    paddingLeft: 50,
  },
  authInputFocused: {
    borderColor: '#15863F',
    borderWidth: 2,
    paddingHorizontal: 17,
    paddingLeft: 49,
  },
  readonlyValue: {
    color: '#1B3023',
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 23,
    paddingVertical: 0,
  },
  input: {
    backgroundColor: '#F9FAFB',
    borderColor: '#EEF0F2',
    borderRadius: 16,
    borderWidth: 1,
    color: '#132017',
    fontSize: 16,
    minHeight: 56,
    paddingHorizontal: 16,
  },
  multilineInput: {
    minHeight: 92,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  inputFocused: {
    borderColor: '#15863F',
    borderWidth: 2,
    paddingHorizontal: 15,
  },
  inputDisabled: {
    backgroundColor: '#F3F4F6',
    color: '#65756B',
  },
  inputInvalid: {
    borderColor: '#B42318',
    borderWidth: 2,
  },
  dateButton: {
    backgroundColor: '#F9FAFB',
    borderColor: '#EEF0F2',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 56,
    paddingHorizontal: 16,
  },
  dateButtonText: {
    color: '#132017',
    fontSize: 16,
  },
  errorText: {
    color: '#B42318',
    fontSize: 14,
    lineHeight: 20,
  },
  authPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#15863F',
    borderRadius: 999,
    justifyContent: 'center',
    marginTop: 4,
    minHeight: 58,
    paddingHorizontal: 18,
    shadowColor: '#15863F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
  },
  authPrimaryButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0,
  },
  noticeText: {
    color: '#15863F',
    fontSize: 14,
    lineHeight: 20,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#15863F',
    borderRadius: 999,
    elevation: 4,
    justifyContent: 'center',
    minHeight: 58,
    paddingHorizontal: 20,
    shadowColor: '#15863F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
  },
  pressedButton: {
    opacity: 0.82,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  statusButton: {
    alignItems: 'center',
    backgroundColor: '#15863F1A',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  statusButtonText: {
    color: '#15863F',
    fontSize: 15,
    fontWeight: '800',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF0F2',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 16,
  },
  cancelButtonText: {
    color: '#566170',
    fontSize: 15,
    fontWeight: '800',
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderColor: '#D92D20',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  dangerButtonText: {
    color: '#B42318',
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryActions: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 2,
  },
  linkButton: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  linkButtonPressed: {
    backgroundColor: '#15863F12',
  },
  divider: {
    backgroundColor: '#C7D2CA',
    height: 18,
    marginHorizontal: 4,
    width: 1,
  },
  linkText: {
    color: '#15863F',
    fontSize: 14,
    fontWeight: '600',
  },
});
