import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#EDF3EA',
  },
  stagesScrollContent: {
    flexGrow: 1,
  },
  stagesScreen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 22,
  },
  stagesTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  backButton: {
    alignItems: 'center',
    borderColor: '#C7D2CA',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 14,
  },
  backButtonText: {
    color: '#2C4B39',
    fontSize: 14,
    fontWeight: '700',
  },
  codeButton: {
    alignItems: 'center',
    backgroundColor: '#2F6848',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 78,
    paddingHorizontal: 16,
  },
  codeButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  headerSpacer: {
    minWidth: 78,
  },
  stagesHeader: {
    marginBottom: 22,
  },
  stagesTitle: {
    color: '#17251C',
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 36,
  },
  stagesSubtitle: {
    color: '#5F7065',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 8,
  },
  stageGrid: {
    gap: 14,
  },
  stageCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 86,
    paddingHorizontal: 18,
    paddingVertical: 16,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
  },
  stageCardPressed: {
    backgroundColor: '#F6FAF4',
    borderColor: '#2F6848',
  },
  stageNumber: {
    color: '#7A8A80',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 8,
  },
  stageName: {
    color: '#1B3023',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 25,
  },
  globalJournalButton: {
    alignItems: 'flex-start',
    backgroundColor: '#2F6848',
    borderColor: '#2F6848',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 62,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  globalJournalButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
  },
  globalJournalButtonMeta: {
    color: '#DCE9DF',
    fontSize: 13,
    fontWeight: '700',
  },
  testClearButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderColor: '#D92D20',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  testClearButtonText: {
    color: '#B42318',
    fontSize: 15,
    fontWeight: '800',
  },
  cardsScrollContent: {
    flexGrow: 1,
  },
  cardsScreen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 22,
  },
  fixedCardsScreen: {
    flex: 1,
  },
  fixedCardsHeader: {
    backgroundColor: '#EDF3EA',
    elevation: 4,
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 10,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    zIndex: 2,
  },
  fixedCardsScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 96,
  },
  fixedAddButtonBar: {
    alignItems: 'center',
    backgroundColor: '#EDF3EA',
    borderTopColor: '#D7E0D8',
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    gap: 12,
    left: 0,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 18,
    position: 'absolute',
    right: 0,
  },
  cultureListHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  headerBackButton: {
    alignItems: 'center',
    borderColor: '#C7D2CA',
    borderRadius: 8,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  headerBackButtonText: {
    color: '#2C4B39',
    fontSize: 34,
    fontWeight: '600',
    lineHeight: 36,
  },
  cultureListTitle: {
    color: '#17251C',
    flex: 1,
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 32,
  },
  cardsHeader: {
    marginBottom: 18,
  },
  cardsTitle: {
    color: '#17251C',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  cardsSubtitle: {
    color: '#5F7065',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 6,
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  searchInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    color: '#132017',
    flex: 1,
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  searchButton: {
    alignItems: 'center',
    backgroundColor: '#DCE9DD',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  searchButtonText: {
    color: '#245039',
    fontSize: 14,
    fontWeight: '800',
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  filterButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 10,
  },
  filterButtonActive: {
    backgroundColor: '#2F6848',
    borderColor: '#2F6848',
  },
  filterButtonText: {
    color: '#2C4B39',
    fontSize: 13,
    fontWeight: '800',
  },
  filterButtonTextActive: {
    color: '#FFFFFF',
  },
  codeInputRow: {
    gap: 10,
  },
  codeInput: {
    width: '100%',
  },
  generateButton: {
    alignItems: 'center',
    backgroundColor: '#DCE9DD',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 14,
  },
  generateButtonText: {
    color: '#245039',
    fontSize: 14,
    fontWeight: '800',
  },
  generateButtonDisabled: {
    backgroundColor: '#E3E9E4',
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: '#2F6848',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 50,
    marginBottom: 18,
  },
  fixedAddButton: {
    marginBottom: 0,
  },
  qrScanButton: {
    alignItems: 'center',
    backgroundColor: '#2F6848',
    borderRadius: 8,
    height: 50,
    justifyContent: 'center',
    width: 58,
  },
  qrIcon: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 3,
    height: 25,
    width: 25,
  },
  qrCorner: {
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
    height: 7,
    width: 7,
  },
  qrCornerSmall: {
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
    height: 5,
    margin: 1,
    width: 5,
  },
  qrDot: {
    backgroundColor: '#FFFFFF',
    borderRadius: 1,
    height: 3,
    margin: 2,
    width: 3,
  },
  calendarScreen: {
    flex: 1,
  },
  calendarContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 110,
  },
  monthBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  monthButton: {
    alignItems: 'center',
    borderColor: '#C7D2CA',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  monthButtonText: {
    color: '#2C4B39',
    fontSize: 12,
    fontWeight: '800',
  },
  monthTitle: {
    color: '#17251C',
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'center',
    textTransform: 'capitalize',
  },
  weekRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  weekDay: {
    color: '#65756B',
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 8,
  },
  dayCell: {
    alignItems: 'center',
    aspectRatio: 1,
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    width: '13.2%',
  },
  dayCellEmpty: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  dayCellMarked: {
    backgroundColor: '#2F6848',
    borderColor: '#2F6848',
  },
  dayCellSelected: {
    backgroundColor: '#193325',
    borderColor: '#193325',
  },
  dayCellText: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '700',
  },
  dayCellTextMarked: {
    color: '#FFFFFF',
  },
  dateActionPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    marginTop: 18,
    padding: 16,
  },
  dateActionTitle: {
    color: '#17251C',
    fontSize: 18,
    fontWeight: '800',
  },
  passportPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 18,
    padding: 16,
  },
  passportTitle: {
    color: '#17251C',
    fontSize: 18,
    fontWeight: '800',
  },
  passportRow: {
    borderTopColor: '#E6EDE7',
    borderTopWidth: 1,
    gap: 3,
    paddingTop: 8,
  },
  passportLabel: {
    color: '#65756B',
    fontSize: 13,
    fontWeight: '700',
  },
  passportValue: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  journalPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginTop: 18,
    padding: 16,
  },
  journalTitle: {
    color: '#17251C',
    fontSize: 18,
    fontWeight: '800',
  },
  journalEmpty: {
    color: '#65756B',
    fontSize: 14,
    lineHeight: 20,
  },
  journalItem: {
    backgroundColor: '#F6FAF4',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 3,
    padding: 12,
  },
  journalItemWarning: {
    backgroundColor: '#FFF7F5',
    borderColor: '#D92D20',
    borderWidth: 2,
  },
  journalItemTitle: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '800',
  },
  journalItemDate: {
    color: '#5F7065',
    fontSize: 13,
    lineHeight: 18,
  },
  journalItemText: {
    color: '#5F7065',
    fontSize: 14,
    lineHeight: 19,
  },
  globalJournalCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  globalJournalCardWarning: {
    backgroundColor: '#FFF7F5',
    borderColor: '#D92D20',
    borderWidth: 2,
  },
  globalJournalCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginHorizontal: -4,
    marginTop: -4,
    padding: 4,
  },
  globalJournalCardTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  globalJournalCardHeaderSide: {
    alignItems: 'flex-end',
    gap: 4,
  },
  globalJournalBadge: {
    backgroundColor: '#2F6848',
    borderRadius: 8,
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    minWidth: 30,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    textAlign: 'center',
  },
  globalJournalToggleText: {
    color: '#2C4B39',
    fontSize: 12,
    fontWeight: '800',
  },
  globalJournalOpenCardButton: {
    alignItems: 'center',
    backgroundColor: '#E8F0EA',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 40,
    paddingHorizontal: 12,
  },
  globalJournalOpenCardButtonText: {
    color: '#245039',
    fontSize: 14,
    fontWeight: '800',
  },
  globalJournalEventList: {
    gap: 8,
    marginTop: 8,
  },
  statusSummary: {
    backgroundColor: '#F6FAF4',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  statusSummaryTitle: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '800',
  },
  statusSummaryText: {
    color: '#5F7065',
    fontSize: 14,
    lineHeight: 19,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  actionChip: {
    alignItems: 'center',
    backgroundColor: '#F6FAF4',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  actionChipActive: {
    backgroundColor: '#2F6848',
    borderColor: '#2F6848',
  },
  actionChipText: {
    color: '#2C4B39',
    fontSize: 13,
    fontWeight: '800',
  },
  actionChipTextActive: {
    color: '#FFFFFF',
  },
  inlineForm: {
    gap: 10,
  },
  chatButton: {
    alignItems: 'center',
    backgroundColor: '#2F6848',
    borderRadius: 8,
    bottom: 22,
    justifyContent: 'center',
    minHeight: 52,
    minWidth: 84,
    paddingHorizontal: 18,
    position: 'absolute',
    right: 20,
  },
  chatButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  plantCardList: {
    gap: 12,
  },
  plantCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 78,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  plantCardWarning: {
    backgroundColor: '#FFF7F5',
    borderColor: '#D92D20',
    borderWidth: 2,
  },
  plantCardName: {
    color: '#1B3023',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
  },
  plantCardCode: {
    color: '#65756B',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  plantCardWarningText: {
    color: '#B42318',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
    marginTop: 6,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    padding: 18,
  },
  emptyStateText: {
    color: '#65756B',
    fontSize: 15,
    fontWeight: '600',
  },
  formPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 16,
    padding: 18,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  noticeBox: {
    backgroundColor: '#FFF7E6',
    borderColor: '#F0C36A',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectButton: {
    backgroundColor: '#FAFCF8',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 16,
  },
  selectButtonDisabled: {
    backgroundColor: '#EEF2EF',
  },
  selectButtonText: {
    color: '#132017',
    fontSize: 16,
  },
  selectPlaceholder: {
    color: '#7C8A80',
  },
  dropdownList: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    maxHeight: 260,
    overflow: 'hidden',
  },
  dropdownItem: {
    borderBottomColor: '#E6EDE7',
    borderBottomWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dropdownItemText: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  dropdownItemMeta: {
    color: '#5F7065',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  sectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  preventionItem: {
    backgroundColor: '#F6FAF4',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  preventionItemTitle: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  preventionItemText: {
    color: '#5F7065',
    fontSize: 14,
    lineHeight: 19,
  },
  preventionEditor: {
    gap: 10,
  },
  inlineActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  inlineActionButton: {
    alignItems: 'center',
    backgroundColor: '#DCE9DD',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  inlineActionButtonText: {
    color: '#245039',
    fontSize: 13,
    fontWeight: '800',
  },
  inlineDangerButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  inlineDangerButtonText: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '800',
  },
  toggleRow: {
    backgroundColor: '#EEF5EF',
    borderRadius: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: 6,
  },
  toggleButton: {
    alignItems: 'center',
    borderRadius: 8,
    flexBasis: '48%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  toggleButtonActive: {
    backgroundColor: '#2F6848',
  },
  toggleButtonText: {
    color: '#526258',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 19,
    textAlign: 'center',
  },
  toggleButtonTextActive: {
    color: '#FFFFFF',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  screen: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 28,
  },
  brand: {
    marginBottom: 26,
  },
  logoMark: {
    alignItems: 'center',
    backgroundColor: '#2F6848',
    borderRadius: 8,
    height: 52,
    justifyContent: 'center',
    marginBottom: 18,
    width: 52,
  },
  logoText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
  },
  header: {
    gap: 7,
  },
  title: {
    color: '#193325',
    fontSize: 33,
    fontWeight: '700',
    lineHeight: 39,
  },
  subtitle: {
    color: '#53665B',
    fontSize: 16,
    lineHeight: 22,
  },
  authPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    padding: 20,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
  },
  formHeader: {
    marginBottom: 22,
  },
  formTitle: {
    color: '#17251C',
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 28,
  },
  formSubtitle: {
    color: '#68766D',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  form: {
    gap: 16,
  },
  field: {
    gap: 4,
  },
  label: {
    color: '#5F7065',
    fontSize: 15,
    fontWeight: '600',
  },
  readonlyValue: {
    color: '#1B3023',
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 23,
    paddingVertical: 0,
  },
  input: {
    backgroundColor: '#FAFCF8',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    color: '#132017',
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: 16,
  },
  multilineInput: {
    minHeight: 92,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  inputFocused: {
    borderColor: '#2F6848',
    borderWidth: 2,
    paddingHorizontal: 15,
  },
  inputDisabled: {
    backgroundColor: '#EEF2EF',
    color: '#65756B',
  },
  inputInvalid: {
    borderColor: '#B42318',
    borderWidth: 2,
  },
  dateButton: {
    backgroundColor: '#FAFCF8',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 16,
  },
  dateButtonText: {
    color: '#132017',
    fontSize: 16,
  },
  errorText: {
    color: '#B42318',
    fontSize: 14,
    lineHeight: 20,
  },
  noticeText: {
    color: '#3B6250',
    fontSize: 14,
    lineHeight: 20,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#2F6848',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 18,
  },
  pressedButton: {
    opacity: 0.82,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  statusButton: {
    alignItems: 'center',
    backgroundColor: '#DCE9DD',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  statusButtonText: {
    color: '#245039',
    fontSize: 15,
    fontWeight: '800',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  cancelButtonText: {
    color: '#2C4B39',
    fontSize: 15,
    fontWeight: '800',
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderColor: '#D92D20',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  dangerButtonText: {
    color: '#B42318',
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryActions: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 2,
  },
  linkButton: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  linkButtonPressed: {
    backgroundColor: '#EEF5EF',
  },
  divider: {
    backgroundColor: '#C7D2CA',
    height: 18,
    marginHorizontal: 4,
    width: 1,
  },
  linkText: {
    color: '#2F6848',
    fontSize: 14,
    fontWeight: '600',
  },
});
