import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#EDF3EA',
    borderTopColor: '#1F2A24',
    borderTopWidth: 3,
  },
  homeSafeArea: {
    backgroundColor: '#F4FAF7',
  },
  authSafeArea: {
    backgroundColor: '#F7FAF9',
  },
  stagesScrollContent: {
    flexGrow: 1,
    paddingBottom: 112,
  },
  stagesScreen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  stagesTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  backButton: {
    alignItems: 'center',
    borderColor: '#C7D2CA',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 14,
  },
  backButtonText: {
    color: '#2C4B39',
    fontSize: 14,
    fontWeight: '700',
  },
  codeButton: {
    alignItems: 'center',
    backgroundColor: '#2F6848',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 78,
    paddingHorizontal: 16,
  },
  codeButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  headerSpacer: {
    minWidth: 78,
  },
  stagesHeader: {
    marginBottom: 22,
  },
  stagesTitle: {
    color: '#17251C',
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 36,
  },
  stagesSubtitle: {
    color: '#5F7065',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 8,
  },
  stageGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    justifyContent: 'space-between',
  },
  stageCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 172,
    paddingHorizontal: 12,
    paddingVertical: 18,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.055,
    shadowRadius: 14,
    width: '48%',
  },
  stageCardPressed: {
    backgroundColor: '#FAFCFB',
    borderColor: '#DCE8E2',
  },
  stageIconBox: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 14,
    height: 78,
    justifyContent: 'center',
    marginBottom: 12,
    width: 78,
  },
  stageIconBoxGreen: {
    backgroundColor: 'transparent',
  },
  stageIconBoxMint: {
    backgroundColor: 'transparent',
  },
  stageIconBoxAqua: {
    backgroundColor: 'transparent',
  },
  stageIconBoxLime: {
    backgroundColor: 'transparent',
  },
  stageIconBoxSky: {
    backgroundColor: 'transparent',
  },
  stageIconBoxOrange: {
    backgroundColor: 'transparent',
  },
  stageIcon: {
    height: 56,
    width: 56,
  },
  stageName: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 21,
    minHeight: 42,
    textAlign: 'center',
  },
  globalJournalButton: {
    alignItems: 'flex-start',
    backgroundColor: '#2F6848',
    borderColor: '#2F6848',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 62,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  globalJournalButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
  },
  globalJournalButtonMeta: {
    color: '#DCE9DF',
    fontSize: 13,
    fontWeight: '700',
  },
  testClearButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderColor: '#D92D20',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  testClearButtonText: {
    color: '#B42318',
    fontSize: 15,
    fontWeight: '800',
  },
  homeNoticeText: {
    color: '#3B6250',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 16,
    textAlign: 'center',
  },
  homeErrorText: {
    color: '#B42318',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 16,
    textAlign: 'center',
  },
  homeTabBar: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderWidth: 1,
    borderBottomWidth: 0,
    bottom: 28,
    flexDirection: 'row',
    height: 76,
    justifyContent: 'space-between',
    left: 0,
    paddingHorizontal: 8,
    position: 'absolute',
    right: 0,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
  },
  homeTabItem: {
    alignItems: 'center',
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minWidth: 0,
  },
  homeTabIconWrap: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    width: 28,
  },
  homeTabBadge: {
    alignItems: 'center',
    backgroundColor: '#EF4444',
    borderColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    height: 16,
    justifyContent: 'center',
    minWidth: 16,
    paddingHorizontal: 4,
    position: 'absolute',
    right: -6,
    top: -5,
  },
  homeTabBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '800',
    lineHeight: 11,
  },
  homeTabText: {
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
  },
  homeTabTextActive: {
    color: '#22C55E',
  },
  homeScannerButton: {
    alignItems: 'center',
    backgroundColor: '#26C95D',
    borderRadius: 24,
    height: 72,
    justifyContent: 'center',
    marginHorizontal: 4,
    marginTop: -36,
    shadowColor: '#16A34A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.26,
    shadowRadius: 16,
    width: 72,
  },
  homeScannerIcon: {
    height: 28,
    width: 28,
  },
  tasksPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 18,
    padding: 14,
  },
  tasksHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tasksScreenContent: {
    flexGrow: 1,
    paddingBottom: 112,
  },
  tasksScreen: {
    flex: 1,
    paddingHorizontal: 20,
  },
  tasksPageHeader: {
    marginBottom: 16,
  },
  tasksPageTitle: {
    color: '#111827',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  tasksPageMeta: {
    color: '#6B7280',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 4,
  },
  tasksList: {
    gap: 12,
  },
  tasksEmptyCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
  },
  tasksEmptyTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
    marginBottom: 4,
  },
  tasksTitle: {
    color: '#17251C',
    fontSize: 18,
    fontWeight: '800',
  },
  tasksBadge: {
    backgroundColor: '#E8F0EA',
    borderRadius: 8,
    color: '#245039',
    fontSize: 13,
    fontWeight: '800',
    minWidth: 30,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    textAlign: 'center',
  },
  tasksBadgeWarning: {
    backgroundColor: '#FFF1F0',
    color: '#B42318',
  },
  tasksEmpty: {
    color: '#65756B',
    fontSize: 14,
    lineHeight: 20,
  },
  taskItem: {
    backgroundColor: '#F6FAF4',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  taskItemWarning: {
    backgroundColor: '#FFF7F5',
    borderColor: '#D92D20',
  },
  taskItemHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  taskItemTitle: {
    color: '#1B3023',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  taskStatus: {
    color: '#245039',
    fontSize: 13,
    fontWeight: '800',
  },
  taskStatusWarning: {
    color: '#B42318',
  },
  taskItemText: {
    color: '#1B3023',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
  },
  taskItemMeta: {
    color: '#65756B',
    fontSize: 13,
    lineHeight: 18,
  },
  tasksMore: {
    color: '#5F7065',
    fontSize: 13,
    fontWeight: '700',
  },
  cardsScrollContent: {
    flexGrow: 1,
  },
  cardsScreen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 22,
  },
  fixedCardsScreen: {
    flex: 1,
    backgroundColor: '#F4FAF7',
  },
  fixedCardsHeader: {
    backgroundColor: '#F4FAF7',
    elevation: 6,
    paddingHorizontal: 28,
    paddingTop: 20,
    paddingBottom: 16,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 14,
    zIndex: 2,
  },
  fixedCardsScrollContent: {
    paddingHorizontal: 28,
    paddingTop: 6,
    paddingBottom: 126,
  },
  fixedAddButtonBar: {
    alignItems: 'center',
    backgroundColor: '#F4FAF7',
    borderTopWidth: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: 18,
    left: 0,
    paddingHorizontal: 28,
    paddingTop: 18,
    paddingBottom: 28,
    position: 'absolute',
    right: 0,
  },
  cultureListHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
    marginBottom: 14,
  },
  headerBackButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#F0F2F4',
    borderRadius: 18,
    borderWidth: 1,
    elevation: 2,
    height: 48,
    justifyContent: 'center',
    shadowColor: '#101828',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    width: 48,
  },
  headerBackButtonText: {
    color: '#6B7280',
    fontSize: 36,
    fontWeight: '600',
    lineHeight: 38,
  },
  headerBackIcon: {
    height: 22,
    width: 22,
  },
  cultureListTitle: {
    color: '#111827',
    flex: 1,
    fontSize: 23,
    fontWeight: '800',
    lineHeight: 29,
  },
  cardsHeader: {
    marginBottom: 18,
  },
  cardsTitle: {
    color: '#17251C',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  cardsSubtitle: {
    color: '#5F7065',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 6,
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 12,
  },
  searchBox: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 18,
    borderWidth: 1,
    elevation: 2,
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 52,
    paddingHorizontal: 16,
    shadowColor: '#101828',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  searchIcon: {
    color: '#9AA3AF',
    fontSize: 19,
    fontWeight: '700',
    lineHeight: 22,
    marginTop: 1,
    textAlign: 'center',
    width: 22,
  },
  searchInput: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    color: '#111827',
    flex: 1,
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 0,
  },
  searchButton: {
    alignItems: 'center',
    backgroundColor: '#DCE9DD',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 72,
    minWidth: 108,
    paddingHorizontal: 20,
  },
  searchButtonText: {
    color: '#245039',
    fontSize: 22,
    fontWeight: '800',
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 18,
  },
  filterScroll: {
    marginBottom: 14,
    marginHorizontal: -28,
  },
  filterScrollContent: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 28,
  },
  filterButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 22,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 16,
    shadowColor: '#101828',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  filterButtonActive: {
    backgroundColor: '#22C55E',
    borderColor: '#22C55E',
    shadowColor: '#16A34A',
    shadowOpacity: 0.18,
  },
  filterButtonText: {
    color: '#6B7280',
    fontSize: 14,
    fontWeight: '800',
  },
  filterButtonTextActive: {
    color: '#FFFFFF',
  },
  filterButtonCount: {
    backgroundColor: '#F3F4F6',
    borderRadius: 13,
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '800',
    minWidth: 28,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    textAlign: 'center',
  },
  filterButtonCountActive: {
    backgroundColor: 'rgba(255,255,255,0.28)',
    color: '#FFFFFF',
  },
  codeInputRow: {
    gap: 10,
  },
  codeInput: {
    width: '100%',
  },
  generateButton: {
    alignItems: 'center',
    backgroundColor: '#DCE9DD',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 14,
  },
  generateButtonText: {
    color: '#245039',
    fontSize: 14,
    fontWeight: '800',
  },
  generateButtonDisabled: {
    backgroundColor: '#E3E9E4',
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: '#2F6848',
    borderRadius: 10,
    flex: 1,
    justifyContent: 'center',
    minHeight: 74,
    marginBottom: 18,
  },
  fixedAddButton: {
    backgroundColor: '#26C95D',
    borderRadius: 16,
    elevation: 5,
    minHeight: 60,
    marginBottom: 0,
    shadowColor: '#16A34A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
  },
  qrScanButton: {
    alignItems: 'center',
    backgroundColor: '#26C95D',
    borderRadius: 24,
    elevation: 8,
    height: 72,
    justifyContent: 'center',
    shadowColor: '#16A34A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.26,
    shadowRadius: 16,
    width: 72,
  },
  qrIcon: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    height: 28,
    width: 28,
  },
  qrCorner: {
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
    height: 8,
    width: 8,
  },
  qrCornerSmall: {
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
    height: 6,
    margin: 1,
    width: 6,
  },
  qrDot: {
    backgroundColor: '#FFFFFF',
    borderRadius: 1,
    height: 4,
    margin: 2,
    width: 4,
  },
  calendarScreen: {
    flex: 1,
  },
  calendarContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 110,
  },
  monthBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  monthButton: {
    alignItems: 'center',
    borderColor: '#C7D2CA',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  monthButtonText: {
    color: '#2C4B39',
    fontSize: 12,
    fontWeight: '800',
  },
  monthTitle: {
    color: '#17251C',
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'center',
    textTransform: 'capitalize',
  },
  weekRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  weekDay: {
    color: '#65756B',
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 8,
  },
  dayCell: {
    alignItems: 'center',
    aspectRatio: 1,
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    width: '13.2%',
  },
  dayCellEmpty: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  dayCellMarked: {
    backgroundColor: '#2F6848',
    borderColor: '#2F6848',
  },
  dayCellSelected: {
    backgroundColor: '#193325',
    borderColor: '#193325',
  },
  dayCellText: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '700',
  },
  dayCellTextMarked: {
    color: '#FFFFFF',
  },
  dateActionPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    marginTop: 18,
    padding: 16,
  },
  dateActionTitle: {
    color: '#17251C',
    fontSize: 18,
    fontWeight: '800',
  },
  passportPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 18,
    padding: 16,
  },
  passportTitle: {
    color: '#17251C',
    fontSize: 18,
    fontWeight: '800',
  },
  passportRow: {
    borderTopColor: '#E6EDE7',
    borderTopWidth: 1,
    gap: 3,
    paddingTop: 8,
  },
  passportLabel: {
    color: '#65756B',
    fontSize: 13,
    fontWeight: '700',
  },
  passportValue: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  warningValue: {
    color: '#B42318',
  },
  journalPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginTop: 18,
    padding: 16,
  },
  journalTitle: {
    color: '#17251C',
    fontSize: 18,
    fontWeight: '800',
  },
  journalEmpty: {
    color: '#65756B',
    fontSize: 14,
    lineHeight: 20,
  },
  journalItem: {
    backgroundColor: '#F6FAF4',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 3,
    padding: 12,
  },
  journalItemWarning: {
    backgroundColor: '#FFF7F5',
    borderColor: '#D92D20',
    borderWidth: 2,
  },
  journalItemTitle: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '800',
  },
  journalItemDate: {
    color: '#5F7065',
    fontSize: 13,
    lineHeight: 18,
  },
  journalItemText: {
    color: '#5F7065',
    fontSize: 14,
    lineHeight: 19,
  },
  globalJournalCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  globalJournalCardWarning: {
    backgroundColor: '#FFF7F5',
    borderColor: '#D92D20',
    borderWidth: 2,
  },
  globalJournalCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginHorizontal: -4,
    marginTop: -4,
    padding: 4,
  },
  globalJournalCardTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  globalJournalCardHeaderSide: {
    alignItems: 'flex-end',
    gap: 4,
  },
  globalJournalBadge: {
    backgroundColor: '#2F6848',
    borderRadius: 8,
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    minWidth: 30,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    textAlign: 'center',
  },
  globalJournalToggleText: {
    color: '#2C4B39',
    fontSize: 12,
    fontWeight: '800',
  },
  globalJournalOpenCardButton: {
    alignItems: 'center',
    backgroundColor: '#E8F0EA',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 40,
    paddingHorizontal: 12,
  },
  globalJournalOpenCardButtonText: {
    color: '#245039',
    fontSize: 14,
    fontWeight: '800',
  },
  globalJournalEventList: {
    gap: 8,
    marginTop: 8,
  },
  statusSummary: {
    backgroundColor: '#F6FAF4',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  statusSummaryTitle: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '800',
  },
  statusSummaryText: {
    color: '#5F7065',
    fontSize: 14,
    lineHeight: 19,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  actionChip: {
    alignItems: 'center',
    backgroundColor: '#F6FAF4',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  actionChipActive: {
    backgroundColor: '#2F6848',
    borderColor: '#2F6848',
  },
  actionChipText: {
    color: '#2C4B39',
    fontSize: 13,
    fontWeight: '800',
  },
  actionChipTextActive: {
    color: '#FFFFFF',
  },
  inlineForm: {
    gap: 10,
  },
  chatButton: {
    alignItems: 'center',
    backgroundColor: '#2F6848',
    borderRadius: 8,
    bottom: 22,
    justifyContent: 'center',
    minHeight: 52,
    minWidth: 84,
    paddingHorizontal: 18,
    position: 'absolute',
    right: 20,
  },
  chatButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0,
  },
  plantCardList: {
    gap: 18,
  },
  plantCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF2F0',
    borderRadius: 24,
    borderWidth: 1,
    elevation: 2,
    minHeight: 92,
    paddingHorizontal: 18,
    paddingVertical: 16,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.045,
    shadowRadius: 10,
  },
  plantCardActive: {
    borderColor: '#A7F3C4',
    borderWidth: 1.5,
  },
  plantCardWarning: {
    backgroundColor: '#FFF7F5',
    borderColor: '#D92D20',
    borderWidth: 2,
  },
  plantCardName: {
    color: '#111827',
    flexShrink: 1,
    fontSize: 19,
    fontWeight: '800',
    lineHeight: 23,
  },
  plantCardCode: {
    color: '#5F7065',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 5,
  },
  plantCardHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
  },
  plantCardStatusPill: {
    backgroundColor: '#22C55E',
    borderRadius: 12,
    color: '#FFFFFF',
    flexShrink: 0,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  plantCardMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    minWidth: 0,
  },
  plantCardCodePill: {
    backgroundColor: '#F3F4F6',
    borderRadius: 7,
    color: '#6B7280',
    flexShrink: 0,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  plantCardMetaText: {
    color: '#9AA3AF',
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
  },
  plantCardWarningText: {
    color: '#B42318',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
    marginTop: 10,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 10,
    borderWidth: 1,
    padding: 24,
  },
  emptyStateText: {
    color: '#65756B',
    fontSize: 18,
    fontWeight: '600',
  },
  formPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 16,
    padding: 18,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  noticeBox: {
    backgroundColor: '#FFF7E6',
    borderColor: '#F0C36A',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectButton: {
    backgroundColor: '#FAFCF8',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 16,
  },
  selectButtonDisabled: {
    backgroundColor: '#EEF2EF',
  },
  selectButtonText: {
    color: '#132017',
    fontSize: 16,
  },
  selectPlaceholder: {
    color: '#7C8A80',
  },
  dropdownList: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    maxHeight: 260,
    overflow: 'hidden',
  },
  dropdownItem: {
    borderBottomColor: '#E6EDE7',
    borderBottomWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dropdownItemText: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  dropdownItemMeta: {
    color: '#5F7065',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  sectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  preventionItem: {
    backgroundColor: '#F6FAF4',
    borderColor: '#D7E0D8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  preventionItemTitle: {
    color: '#1B3023',
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  preventionItemText: {
    color: '#5F7065',
    fontSize: 14,
    lineHeight: 19,
  },
  preventionEditor: {
    gap: 10,
  },
  inlineActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  inlineActionButton: {
    alignItems: 'center',
    backgroundColor: '#DCE9DD',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  inlineActionButtonText: {
    color: '#245039',
    fontSize: 13,
    fontWeight: '800',
  },
  inlineDangerButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  inlineDangerButtonText: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '800',
  },
  toggleRow: {
    backgroundColor: '#EEF5EF',
    borderRadius: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: 6,
  },
  toggleButton: {
    alignItems: 'center',
    borderRadius: 8,
    flexBasis: '48%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  toggleButtonActive: {
    backgroundColor: '#2F6848',
  },
  toggleButtonText: {
    color: '#526258',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 19,
    textAlign: 'center',
  },
  toggleButtonTextActive: {
    color: '#FFFFFF',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  screen: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  brand: {
    alignItems: 'center',
    marginBottom: 40,
  },
  logoMark: {
    alignItems: 'center',
    backgroundColor: '#F0FFF6',
    borderRadius: 18,
    height: 72,
    justifyContent: 'center',
    marginBottom: 14,
    shadowColor: '#CCF8DE',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.26,
    shadowRadius: 18,
    width: 72,
  },
  logoImage: {
    height: 38,
    width: 38,
  },
  header: {
    alignItems: 'center',
  },
  title: {
    color: '#101828',
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 36,
    textAlign: 'center',
  },
  subtitle: {
    color: '#53665B',
    fontSize: 16,
    lineHeight: 22,
  },
  authPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#F0F2F4',
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 28,
    paddingBottom: 28,
    paddingTop: 26,
    shadowColor: '#102015',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.06,
    shadowRadius: 24,
  },
  formHeader: {
    marginBottom: 8,
  },
  formTitle: {
    color: '#566170',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 20,
  },
  form: {
    gap: 22,
  },
  field: {
    gap: 8,
  },
  label: {
    color: '#566170',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 20,
  },
  passwordRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  forgotPasswordText: {
    color: '#13A84B',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  authInput: {
    backgroundColor: '#F9FAFB',
    borderColor: '#EEF0F2',
    borderRadius: 16,
    borderWidth: 1,
    color: '#101828',
    fontSize: 16,
    minHeight: 56,
    paddingHorizontal: 18,
    shadowColor: '#101828',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  authInputFocused: {
    borderColor: '#22C55E',
    borderWidth: 2,
    paddingHorizontal: 17,
  },
  readonlyValue: {
    color: '#1B3023',
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 23,
    paddingVertical: 0,
  },
  input: {
    backgroundColor: '#FAFCF8',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    color: '#132017',
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: 16,
  },
  multilineInput: {
    minHeight: 92,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  inputFocused: {
    borderColor: '#2F6848',
    borderWidth: 2,
    paddingHorizontal: 15,
  },
  inputDisabled: {
    backgroundColor: '#EEF2EF',
    color: '#65756B',
  },
  inputInvalid: {
    borderColor: '#B42318',
    borderWidth: 2,
  },
  dateButton: {
    backgroundColor: '#FAFCF8',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 16,
  },
  dateButtonText: {
    color: '#132017',
    fontSize: 16,
  },
  errorText: {
    color: '#B42318',
    fontSize: 14,
    lineHeight: 20,
  },
  authPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#26C95D',
    borderRadius: 16,
    justifyContent: 'center',
    marginTop: 4,
    minHeight: 58,
    paddingHorizontal: 18,
    shadowColor: '#16A34A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
  },
  authPrimaryButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0,
  },
  noticeText: {
    color: '#3B6250',
    fontSize: 14,
    lineHeight: 20,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#2F6848',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 18,
  },
  pressedButton: {
    opacity: 0.82,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  statusButton: {
    alignItems: 'center',
    backgroundColor: '#DCE9DD',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  statusButtonText: {
    color: '#245039',
    fontSize: 15,
    fontWeight: '800',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#CAD6CE',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  cancelButtonText: {
    color: '#2C4B39',
    fontSize: 15,
    fontWeight: '800',
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderColor: '#D92D20',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  dangerButtonText: {
    color: '#B42318',
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryActions: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 2,
  },
  linkButton: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  linkButtonPressed: {
    backgroundColor: '#EEF5EF',
  },
  divider: {
    backgroundColor: '#C7D2CA',
    height: 18,
    marginHorizontal: 4,
    width: 1,
  },
  linkText: {
    color: '#2F6848',
    fontSize: 14,
    fontWeight: '600',
  },
});
