// Фабрики пустых форм домена.
import { getTodayIsoDate } from './dates';

export function createEmptyCultureForm() {
  return {
    createdAt: getTodayIsoDate(),
    cultureName: '',
    speciesName: '',
    varietyName: '',
    code: '',
    quantity: '',
    hasHormone: false,
    sourcePlantName: '',
    sourceMaterial: '',
    locationDescription: '',
    parentBatch: '',
    sterilityStatus: 'unchecked',
    startPhotoNote: '',
    startPhotoUri: '',
    startPhotoUris: [],
    batchStatus: '',
    qrStatus: 'none',
  };
}

export function createEmptyStatusForm() {
  return {
    rootedCount: '',
    transplantCount: '',
    propagationCount: '',
    saleCount: '',
    deathCount: '',
    discardCount: '',
    lossCount: '',
    reason: '',
    lossReason: '',
    comment: '',
    photoNote: '',
    photoUri: '',
    photoUris: [],
    saleType: '',
    recipient: '',
    saleAmount: '',
    propagationMethod: '',
    stressLevel: '',
    conditionDescription: '',
    environmentTemperature: '',
    environmentHumidity: '',
    environmentAirHumidity: '',
    substrateHumidity: '',
    environmentLight: '',
    ventilation: '',
    humidityReduction: '',
    turgor: '',
    stability: '',
    careType: '',
    growthRate: '',
    riskLevel: '',
    careIntervalDays: '',
    wateringIntervalDays: '',
    diseaseName: '',
    pestName: '',
    diseaseSeverity: '',
    waterVolume: '',
    applicationMethod: '',
    productName: '',
    dosage: '',
    plantReaction: '',
    placement: '',
    densityChange: '',
    greenhouseName: '',
    rackName: '',
    shelfName: '',
    movementComment: '',
  };
}

export function createEmptyIntroActionForm() {
  return {
    comment: '',
    photoNote: '',
    photoUri: '',
    photoUris: [],
    contaminationNote: '',
    lossCount: '',
    lossReason: '',
    greenhouseName: '',
    rackName: '',
    shelfName: '',
    movementComment: '',
    quarantineReason: '',
    deathCount: '',
    deathReason: '',
  };
}
